<?php $editing=!!$box; $stockUnlimited=$editing && isset($box['track_inventory']) && !(bool)$box['track_inventory']; ?>
<section class="admin-page-head"><div><p class="eyebrow">GIFT BOX / CUTIE</p><h1><?= $editing?'Editează cutia':'Cutie nouă' ?></h1><p>Cutia poate fi folosită în configurator și oferită direct pe pagina unui produs.</p></div><a class="admin-button secondary" href="<?= e(url('/admin/gift-box')) ?>">Înapoi</a></section>
<?php if($notice): ?><div class="admin-alert success"><?= e($notice) ?></div><?php endif; ?><?php if($error): ?><div class="admin-alert error"><?= e($error) ?></div><?php endif; ?>
<form class="admin-form-layout" enctype="multipart/form-data" method="post" action="<?= e(url($editing?'/admin/gift-box/cutii/'.$box['id']:'/admin/gift-box/cutii')) ?>"><?= csrf_field() ?>
    <div>
        <section class="admin-panel" data-gift-box-stock-editor><h2>Detalii cutie</h2><div class="admin-form-grid"><label>Nume cutie<input name="name" required value="<?= e($box['name']??'') ?>" placeholder="ex. Cutia Ivory"></label><label>Slug<input name="slug" value="<?= e($box['slug']??'') ?>" placeholder="generat din nume"></label><label>Preț cutie (lei)<input type="number" step="0.01" min="0" name="price" required value="<?= number_format((int)($box['price_minor']??$box['base_price_minor']??0)/100,2,'.','') ?>"></label><label data-gift-box-stock-field>Stoc cutii<input type="number" min="0" name="stock_qty" required value="<?= (int)($box['current_stock']??$box['stock_qty']??0) ?>" <?= $stockUnlimited?'readonly':'' ?> data-gift-box-stock-input><small data-gift-box-stock-help><?= $stockUnlimited?'Disponibilitatea online nu este limitată de această valoare.':'Numărul disponibil pentru comenzile online.' ?></small></label><label>Min. produse în cutie<input type="number" min="0" name="min_components" value="<?= (int)($box['min_components']??2) ?>"></label><label>Max. produse în cutie<input type="number" min="1" name="max_components" value="<?= (int)($box['max_components']??6) ?>"></label><label>Ordine<input type="number" name="sort_order" value="<?= (int)($box['sort_order']??0) ?>"></label><label class="wide admin-switch-row gift-box-unlimited-toggle"><input type="checkbox" name="stock_unlimited" value="1" <?= $stockUnlimited?'checked':'' ?> data-gift-box-unlimited-toggle><span class="admin-switch" aria-hidden="true"><i></i></span><span><b>Stoc online nelimitat</b><small>Cutia rămâne disponibilă pe website chiar dacă stocul contabil este 0.</small></span></label><label class="wide">Descriere<textarea name="description" placeholder="Un scurt text despre cutie"><?= e($box['description']??'') ?></textarea></label></div></section>
        <section class="admin-panel gift-box-dimensions-panel">
            <div class="panel-head"><div><p class="eyebrow">DIMENSIUNI EXTERIOARE</p><h2>Mărimea cutiei</h2><p class="help">Completează dimensiunile reale ale cutiei, în centimetri.</p></div><span class="gift-box-dimension-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m4 8 8-4 8 4-8 4-8-4Zm0 0v9l8 4 8-4V8M12 12v9"/><path d="M2 4h5M2 4l2-2M2 4l2 2M17 20h5m0 0-2-2m2 2-2 2"/></svg></span></div>
            <div class="gift-box-dimension-grid">
                <label><span>Lungime <em>opțional</em></span><div><input type="number" name="length_cm" min="0.01" max="9999" step="0.01" inputmode="decimal" value="<?= e((string)($box['length_cm']??'')) ?>" placeholder="ex. 27"><b>cm</b></div><small>Latura cea mai lungă</small></label>
                <label><span>Lățime <em>opțional</em></span><div><input type="number" name="width_cm" min="0.01" max="9999" step="0.01" inputmode="decimal" value="<?= e((string)($box['width_cm']??'')) ?>" placeholder="ex. 17"><b>cm</b></div><small>Latura frontală</small></label>
                <label><span>Înălțime <em>opțional</em></span><div><input type="number" name="height_cm" min="0.01" max="9999" step="0.01" inputmode="decimal" value="<?= e((string)($box['height_cm']??'')) ?>" placeholder="ex. 7.2"><b>cm</b></div><small>Cutia închisă</small></label>
            </div>
            <div class="gift-box-dimension-preview"><span aria-hidden="true">L × l × h</span><p><strong>Format salvat</strong><small>Dimensiunile vor putea fi folosite pentru prezentare, ambalare și livrare.</small></p></div>
        </section>
        <section class="admin-panel gift-box-rule-builder coupon-rule-builder" data-coupon-builder>
            <div class="coupon-rule-head"><div><span class="coupon-rule-icon" aria-hidden="true">◇</span><div><strong>Produse eligibile pentru această cutie</strong><small>Regula se aplică exclusiv în configuratorul Gift Box.</small></div></div><button type="button" class="admin-button secondary" data-coupon-picker-open aria-controls="gift-box-products-picker">Alege produsele</button></div>
            <div class="coupon-rule-summary"><div><small>Categorii</small><div data-coupon-category-summary><span>Nicio categorie selectată</span></div></div><div><small>Colecții</small><div data-coupon-collection-summary><span>Nicio colecție selectată</span></div></div><div><small>Produse</small><div data-coupon-product-summary><span>Niciun produs selectat</span></div></div></div>
            <p class="coupon-rule-note gift-box-all-products-note" data-coupon-scope-note><span>i</span> Dacă nu selectezi nimic, toate produsele active vor fi eligibile în configurator. Oferta directă de pe pagina unui produs nu este filtrată aici.</p>
            <div id="gift-box-products-picker" class="coupon-picker-modal gift-box-admin-picker" data-coupon-picker hidden>
                <button class="coupon-picker-backdrop" type="button" data-coupon-picker-close aria-label="Închide selectorul"></button>
                <section class="coupon-picker-dialog" role="dialog" aria-modal="true" aria-labelledby="gift-box-products-title">
                    <header><div><p class="eyebrow">CATALOG GIFT BOX</p><h2 id="gift-box-products-title">Alege produsele pentru cutie</h2><p>Selecția este valabilă numai pentru această cutie.</p></div><button class="coupon-picker-close" type="button" data-coupon-picker-close aria-label="Închide">×</button></header>
                    <div class="coupon-picker-toolbar"><label><span class="sr-only">Caută produse</span><input type="search" placeholder="Caută un produs…" data-coupon-product-search></label><button type="button" data-coupon-all-catalog>Toate produsele</button><button type="button" data-coupon-select-visible>Selectează afișate</button><button type="button" data-coupon-clear-visible>Curăță afișate</button></div>
                    <div class="coupon-picker-layout">
                        <aside class="coupon-category-panel"><div class="coupon-filter-groups"><section><strong>Categorii</strong><div class="coupon-category-tabs"><button type="button" class="is-active" data-coupon-filter-kind="all" data-coupon-filter-id="">Toate produsele <span><?= count($products) ?></span></button><?php foreach($categories as $category): $categoryCount=count(array_filter($products,static fn(array $product):bool=>in_array((int)$category['id'],array_map('intval',array_filter(explode(',',(string)$product['category_ids']))),true))); ?><button type="button" data-coupon-filter-kind="category" data-coupon-filter-id="<?= (int)$category['id'] ?>"><?= e($category['name']) ?><span><?= $categoryCount ?></span></button><?php endforeach; ?></div></section><section><strong>Colecții</strong><div class="coupon-category-tabs"><?php foreach($collections as $collection): $collectionCount=count(array_filter($products,static fn(array $product):bool=>in_array((int)$collection['id'],array_map('intval',array_filter(explode(',',(string)$product['collection_ids']))),true))); ?><button type="button" data-coupon-filter-kind="collection" data-coupon-filter-id="<?= (int)$collection['id'] ?>"><?= e($collection['name']) ?><span><?= $collectionCount ?></span></button><?php endforeach; ?></div></section></div></aside>
                        <div class="coupon-picker-content">
                            <div class="coupon-category-actions"><?php foreach($categories as $category): ?><article data-coupon-scope-kind="category" data-coupon-scope-id="<?= (int)$category['id'] ?>" hidden><label><input type="checkbox" name="category_ids[]" value="<?= (int)$category['id'] ?>" data-coupon-category <?= in_array((int)$category['id'],$selectedCategoryIds,true)?'checked':'' ?>><span><strong>Toată categoria „<?= e($category['name']) ?>”</strong><small>Include produsele actuale și viitoare din categorie.</small></span></label></article><?php endforeach; ?><?php foreach($collections as $collection): ?><article data-coupon-scope-kind="collection" data-coupon-scope-id="<?= (int)$collection['id'] ?>" hidden><label><input type="checkbox" name="collection_ids[]" value="<?= (int)$collection['id'] ?>" data-coupon-collection <?= in_array((int)$collection['id'],$selectedCollectionIds,true)?'checked':'' ?>><span><strong>Toată colecția „<?= e($collection['name']) ?>”</strong><small>Include produsele actuale și viitoare din colecție.</small></span></label></article><?php endforeach; ?></div>
                            <div class="coupon-product-grid gift-box-admin-product-grid"><?php foreach($products as $product): ?><label class="coupon-product-choice catalog-product-visual gift-box-admin-product" data-coupon-product-card data-product-name="<?= e(mb_strtolower($product['name'])) ?>" data-product-categories="<?= e($product['category_ids']) ?>" data-product-collections="<?= e($product['collection_ids']) ?>"><input type="checkbox" name="product_ids[]" value="<?= (int)$product['id'] ?>" data-coupon-product <?= in_array((int)$product['id'],$selectedProductIds,true)?'checked':'' ?>><span class="coupon-product-check">✓</span><img src="<?= e(url($product['image_path'])) ?>" alt="<?= e($product['name']) ?>" width="240" height="240" loading="lazy"><strong><?= e($product['name']) ?></strong><small>Produs individual</small></label><?php endforeach; ?></div>
                            <div class="coupon-products-empty" data-coupon-products-empty hidden>Nu există produse pentru filtrul ales.</div>
                        </div>
                    </div>
                    <footer><p><strong data-coupon-selection-count>0</strong> selecții configurate</p><button class="admin-button" type="button" data-coupon-picker-apply>Aplică selecția</button></footer>
                </section>
            </div>
        </section>
    </div>
    <aside>
        <section class="admin-panel"><h2>Publicare</h2><label class="check-label"><input type="checkbox" name="is_active" value="1" <?= !isset($box['is_active'])||$box['is_active']?'checked':'' ?>> Cutie activă în configurator</label><button class="admin-button" type="submit">Salvează cutia</button></section>
        <section class="admin-panel"><h2>Imagine cutie</h2><?php if(!empty($box['image_path'])): ?><img class="admin-preview-image" src="<?= e(url($box['image_path'])) ?>" alt="" width="260" height="180"><?php endif; ?><input type="file" name="image" accept="image/jpeg,image/png,image/webp"><p class="help">JPG, PNG sau WebP, maximum 8 MB. Imaginea apare la pasul „Alege cutia”.</p></section>
    </aside>
</form>
