<?php
$statusLabels=['Confirmed'=>'Confirmat','PartiallyReceived'=>'Recepționat parțial','Reversed'=>'Inversat'];
$statusClasses=['Confirmed'=>'success','PartiallyReceived'=>'warning','Reversed'=>'danger'];
$isFinal=in_array($document['status'],array_keys($statusLabels),true);
$address=json_decode((string)($document['supplier_address_snapshot_json']??''),true)?:[];
$hasDifferences=count(array_filter($lines,static fn($line)=>($line['difference_type']??'none')!=='none'));
?>
<section class="admin-page-head accounting-page-head accounting-page-head-compact">
  <div><p class="eyebrow">NOTĂ DE RECEPȚIE</p><h1><?= e($document['formatted_number']?:'NIR #'.$document['id']) ?></h1><p>Document contabil imuabil, separat de stocul comercial.</p></div>
  <div class="button-row"><a class="admin-button secondary" href="<?= e(url('/admin/nir-uri')) ?>">Înapoi</a><?php if($isFinal): ?><a class="admin-button secondary" target="_blank" href="<?= e(url('/admin/nir-uri/'.$document['id'].'/pdf')) ?>">PDF</a><a class="admin-button" href="<?= e(url('/admin/nir-uri/'.$document['id'].'/xlsx')) ?>">Exportă XLSX</a><?php endif; ?></div>
</section>
<?php if($notice): ?><div class="admin-alert success"><?= e($notice) ?></div><?php endif; ?>
<?php if($error): ?><div class="admin-alert error"><?= e($error) ?></div><?php endif; ?>

<section class="nir-document-summary">
  <article class="primary"><small>Document</small><strong><?= e($document['formatted_number']?:'Nealocat') ?></strong><span class="status-pill <?= e($statusClasses[$document['status']]??'') ?>"><?= e($statusLabels[$document['status']]??$document['status']) ?></span></article>
  <article><small>Recepție</small><strong><?= date('d.m.Y',strtotime($document['receipt_date'])) ?></strong><span><?= e($document['warehouse_name']) ?></span></article>
  <article><small>Furnizor</small><strong><?= e($document['supplier_name_snapshot']) ?></strong><span>CUI <?= e($document['supplier_tax_id_snapshot']) ?></span></article>
  <article><small>Factura furnizorului</small><strong><?= e(trim($document['invoice_series'].' '.$document['invoice_number'])) ?></strong><span><?= date('d.m.Y',strtotime($document['invoice_date'])) ?></span></article>
  <article class="total"><small>Total document</small><strong><?= number_format((float)$document['grand_total'],2,',','.') ?> <?= e($document['currency']) ?></strong><span>TVA <?= number_format((float)$document['vat_total'],2,',','.') ?></span></article>
</section>

<?php if($document['is_late_entered']): ?><div class="admin-alert warning"><strong>Document introdus ulterior.</strong> <?= e($document['late_entry_reason']) ?></div><?php endif; ?>
<?php if($document['document_kind']==='reversal'): ?><div class="admin-alert error" data-admin-status-banner><strong>Document de inversare.</strong> <?= e($document['reversal_reason']) ?> · NIR inițial <?= e($document['original_formatted_number']?:'#'.(int)$document['original_nir_id']) ?></div><?php elseif($document['status']==='Reversed'): ?><div class="admin-alert error" data-admin-status-banner><strong>NIR inversat.</strong> <?= e($document['reversal_reason']) ?><?= !empty($document['reversal_formatted_number'])?' · Document: '.e($document['reversal_formatted_number']):'' ?></div><?php endif; ?>

<div class="accounting-subpanel-row nir-show-subpanels">
  <details class="accounting-subpanel"><summary><span><b>Detalii furnizor</b><small>Adresă și operator</small></span><i>+</i></summary><dl class="accounting-detail-list accounting-subpanel-content"><div><dt>CUI</dt><dd><?= e($document['supplier_tax_id_snapshot']) ?></dd></div><div><dt>Adresă</dt><dd><?= e($address['line1']??'—') ?></dd></div><div><dt>Creat de</dt><dd><?= e(trim((string)$document['creator_name'])?:'Sistem') ?></dd></div><div><dt>Confirmat de</dt><dd><?= e(trim((string)$document['confirmer_name'])?:'—') ?></dd></div></dl></details>
  <details class="accounting-subpanel"><summary><span><b>Detalii factură și aviz</b><small>Scadență, monedă și documente</small></span><i>+</i></summary><dl class="accounting-detail-list accounting-subpanel-content"><div><dt>Data facturii</dt><dd><?= date('d.m.Y',strtotime($document['invoice_date'])) ?></dd></div><div><dt>Scadență</dt><dd><?= $document['due_date']?date('d.m.Y',strtotime($document['due_date'])):'—' ?></dd></div><div><dt>Monedă / curs</dt><dd><?= e($document['currency'].' / '.$document['exchange_rate']) ?></dd></div><div><dt>Aviz</dt><dd><?= e($document['delivery_note_number']?:'—') ?></dd></div></dl></details>
  <details class="accounting-subpanel" <?= $artifacts?'':'disabled' ?>><summary><span><b>Documente atașate</b><small><?= count($artifacts) ?> fișiere arhivate</small></span><i>+</i></summary><div class="accounting-artifacts accounting-subpanel-content"><?php foreach($artifacts as $artifact): ?><a href="<?= e(url('/admin/nir-uri/'.$document['id'].'/atasament/'.$artifact['id'])) ?>"><strong><?= e(strtoupper($artifact['artifact_type'])) ?></strong><span>v<?= (int)$artifact['document_version'] ?> · <?= number_format((int)$artifact['size_bytes']/1024,1,',','.') ?> KB</span><small><?= e(substr($artifact['sha256'],0,16)) ?>…</small></a><?php endforeach; ?><?php if(!$artifacts): ?><p class="help">Nu există fișiere atașate.</p><?php endif; ?></div></details>
</div>

<section class="admin-panel accounting-table-panel accounting-register-panel">
  <div class="panel-head accounting-panel-head-compact"><div><h2>Produsele recepționate</h2><p class="help"><?= count($lines) ?> poziții · <?= $hasDifferences ?> cu diferențe.</p></div><span class="status-pill">Snapshot confirmat</span></div>
  <div class="admin-table-wrap"><table class="admin-table accounting-compact-table nir-reception-table"><thead><tr><th>Produs asociat</th><th>Denumire furnizor</th><th>Cantități</th><th>Diferențe</th><th>Valori</th></tr></thead><tbody>
  <?php foreach($lines as $line): ?>
    <tr><td><strong><?= e($line['product_name_snapshot']) ?></strong><small><?= e($line['variant_name_snapshot']?:'Varianta standard') ?> · SKU <?= e($line['sku_snapshot']?:'—') ?></small></td><td><?= e($line['supplier_product_name']) ?><small><?= e($line['online_stock_mode_snapshot']==='unlimited'?'Online nelimitat':'Online limitat') ?></small></td><td><span class="nir-quantity-stack"><b>Facturat <?= number_format((float)$line['invoiced_quantity'],0,',','.') ?></b><b>Recepționat <?= number_format((float)$line['received_quantity'],0,',','.') ?></b><strong>Acceptat <?= number_format((float)$line['accepted_quantity'],0,',','.') ?> <?= e($line['unit_of_measure_snapshot']) ?></strong></span></td><td><?php if($line['difference_type']==='none'): ?><span class="status-pill success">Fără diferențe</span><?php else: ?><span class="status-pill warning"><?= e($line['difference_type']) ?></span><small><?= e($line['difference_reason']) ?></small><?php endif; ?></td><td><strong><?= number_format((float)$line['total_with_vat'],2,',','.') ?> <?= e($document['currency']) ?></strong><small><?= number_format((float)$line['unit_purchase_price_without_vat'],2,',','.') ?> / unitate · TVA <?= number_format((float)$line['vat_value'],2,',','.') ?></small></td></tr>
  <?php endforeach; ?>
  </tbody></table></div>
  <div class="accounting-totals"><span>Fără TVA <strong><?= number_format((float)$document['total_without_vat'],2,',','.') ?> <?= e($document['currency']) ?></strong></span><span>TVA <strong><?= number_format((float)$document['vat_total'],2,',','.') ?> <?= e($document['currency']) ?></strong></span><span>Total <strong><?= number_format((float)$document['grand_total'],2,',','.') ?> <?= e($document['currency']) ?></strong></span></div>
</section>

<details class="admin-panel accounting-collapsible" <?= $movements?'open':'' ?>>
  <summary><span><i><?= count($movements) ?></i><span><strong>Mișcări generate în Stocuri Conta</strong><small>Registrul este append-only; mișcările originale nu se editează.</small></span></span><b>Vezi detalii</b></summary>
  <div class="accounting-collapsible-body"><div class="admin-table-wrap"><table class="admin-table accounting-compact-table"><thead><tr><th>Data</th><th>Tip</th><th>Produs</th><th>Intrare</th><th>Ieșire</th><th>Cost</th><th>Postat</th></tr></thead><tbody><?php foreach($movements as $movement): ?><tr><td><?= date('d.m.Y',strtotime($movement['effective_date'])) ?></td><td><span class="status-pill"><?= e($movement['movement_type']) ?></span></td><td><a href="<?= e(url('/admin/stocuri-conta/fisa/'.$movement['product_variant_id'])) ?>"><?= e($movement['sku_snapshot']) ?></a></td><td><?= number_format((float)$movement['quantity_in'],0,',','.') ?> buc</td><td><?= number_format((float)$movement['quantity_out'],0,',','.') ?> buc</td><td><?= number_format((float)$movement['source_unit_cost'],2,',','.') ?></td><td><?= date('d.m.Y H:i',strtotime($movement['posted_at'])) ?></td></tr><?php endforeach; ?><?php if(!$movements): ?><tr><td colspan="7">Nu există mișcări generate de acest document.</td></tr><?php endif; ?></tbody></table></div></div>
</details>

<?php if(in_array($document['status'],['Draft','RequiresProductMapping','InReception','ReadyForConfirmation'],true)): ?><section class="accounting-final-action"><div><p class="eyebrow">DOCUMENT ÎN LUCRU</p><h2>Confirmă NIR-ul</h2><p>Confirmarea alocă numărul final și postează cantitățile acceptate.</p></div><form method="post" action="<?= e(url('/admin/nir-uri/'.$document['id'].'/confirmare')) ?>"><?= csrf_field() ?><input type="hidden" name="row_version" value="<?= (int)$document['row_version'] ?>"><button class="admin-button" type="submit">Confirmă NIR</button></form></section><?php endif; ?>

<?php if(in_array($document['status'],['Confirmed','PartiallyReceived'],true)&&MaisonBebe\Core\Auth::hasPermission('nir.reverse')): ?>
<section class="accounting-final-action accounting-reversal-action"><div><p class="eyebrow">CORECȚIE CONTROLATĂ</p><h2>Ai nevoie să inversezi documentul?</h2><p>NIR-ul original rămâne intact; se creează un document nou cu mișcări inverse.</p></div><button class="admin-button secondary" type="button" data-open-accounting-modal="nir-reversal">Deschide inversarea</button></section>
<div class="accounting-modal" data-accounting-modal="nir-reversal" hidden><button class="accounting-modal-backdrop" type="button" data-close-accounting-modal aria-label="Închide"></button><section class="accounting-modal-card accounting-modal-card-small" role="dialog" aria-modal="true" aria-labelledby="nir-reversal-title"><header><div><p class="eyebrow">OPERAȚIUNE DE CORECȚIE</p><h2 id="nir-reversal-title">Inversează NIR-ul</h2><p>Introdu data efectivă și motivul complet.</p></div><button type="button" data-close-accounting-modal aria-label="Închide">×</button></header><form method="post" action="<?= e(url('/admin/nir-uri/'.$document['id'].'/inversare')) ?>"><?= csrf_field() ?><div class="accounting-modal-form"><label>Data efectivă<input type="date" name="reversal_date" max="<?= date('Y-m-d') ?>" value="<?= date('Y-m-d') ?>" required></label><label>Motiv<textarea name="reason" required></textarea></label></div><footer><button class="admin-button secondary" type="button" data-close-accounting-modal>Anulează</button><button class="admin-button danger" type="submit">Creează inversarea</button></footer></form></section></div>
<?php endif; ?>
