<!doctype html><html lang="ro"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?= e($title??'Admin Maison Bébé') ?></title><link rel="icon" type="image/png" href="<?= e(asset('images/maison-bebe-favicon.png?v=20260711-02')) ?>"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600&family=Playfair+Display:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="<?= e(asset('css/admin.css?v=20260713-12')) ?>"><meta name="csrf-token" content="<?= e(MaisonBebe\Core\Csrf::token()) ?>"></head><body class="admin-body"><button class="admin-menu-toggle" type="button" data-admin-menu aria-expanded="false" aria-controls="admin-sidebar">☰ <span>Meniu</span></button><aside id="admin-sidebar" class="admin-sidebar"><a class="admin-brand" href="<?= e(url('/admin')) ?>"><strong>MAISON BÉBÉ</strong><small>ADMINISTRARE MAGAZIN</small></a><nav>
<?php if(MaisonBebe\Core\Auth::hasPermission('dashboard.view')||MaisonBebe\Core\Auth::hasPermission('orders.view')||MaisonBebe\Core\Auth::hasPermission('shipping.manage')): ?><span>Activitate zilnică</span><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('dashboard.view')): ?><a href="<?= e(url('/admin')) ?>">Prezentare generală</a><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('orders.view')): ?><a href="<?= e(url('/admin/comenzi')) ?>">Comenzi</a><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('dashboard.view')): ?><a href="<?= e(url('/admin/notificari')) ?>">Notificări <b data-admin-notification-count></b></a><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('shipping.manage')): ?><a href="<?= e(url('/admin/expeditii')) ?>">Expediții</a><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('products.view')||MaisonBebe\Core\Auth::hasPermission('categories.manage')||MaisonBebe\Core\Auth::hasPermission('customers.view')): ?><span>Produse și clienți</span><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('products.view')): ?><a href="<?= e(url('/admin/produse')) ?>">Produse</a><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('categories.manage')): ?><a href="<?= e(url('/admin/categorii')) ?>">Categorii &amp; Colecții</a><a href="<?= e(url('/admin/gift-box')) ?>">Gift Box și cutii</a><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('customers.view')): ?><a href="<?= e(url('/admin/clienti')) ?>">Clienți</a><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('products.update')): ?><a href="<?= e(url('/admin/cupoane')) ?>">Cupoane</a><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('cms.manage')||MaisonBebe\Core\Auth::hasPermission('atelier.manage')): ?><span>Conținut</span><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('cms.manage')): ?><a href="<?= e(url('/admin/cms')) ?>">Pagini și texte</a><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('atelier.manage')): ?><a href="<?= e(url('/admin/atelier')) ?>">Atelier</a><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('billing.view')): ?><span>Bani și documente</span><a href="<?= e(url('/admin/facturare')) ?>">Configurare facturi</a><a href="<?= e(url('/admin/facturi')) ?>">Facturi emise</a><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('seo.manage')||MaisonBebe\Core\Auth::hasPermission('settings.manage')): ?><span>Setări magazin</span><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('seo.manage')): ?><a href="<?= e(url('/admin/seo/indexabilitate')) ?>">SEO</a><?php endif; ?>
<?php if(MaisonBebe\Core\Auth::hasPermission('settings.manage')): ?><a href="<?= e(url('/admin/setari/email')) ?>">Email</a><a href="<?= e(url('/admin/setari/plati')) ?>">Plăți</a><a href="<?= e(url('/admin/setari/livrare')) ?>">Livrare</a><a href="<?= e(url('/admin/setari/autentificare')) ?>">Autentificare</a><a href="<?= e(url('/admin/utilizatori')) ?>">Utilizatori &amp; acces</a><?php endif; ?>
<a href="<?= e(url('/admin/setari/securitate')) ?>">Securitate cont</a>
</nav></aside><div class="admin-app"><header class="admin-topbar"><div><p><strong>Administrare</strong></p></div><div><?php if(MaisonBebe\Core\Auth::hasPermission('products.create')): ?><a class="admin-button admin-quick-add" href="<?= e(url('/admin/produse/creare')) ?>"><span>＋</span><b>Produs nou</b></a><?php endif; ?><button type="button" class="browser-notify-button" data-enable-browser-notifications>Activează notificările</button><a class="admin-store-link" href="<?= e(url('/')) ?>" target="_blank">Vezi magazinul ↗</a><span><?= e(($adminUser['first_name']??'Admin').' '.($adminUser['last_name']??'')) ?></span><details class="admin-help-menu"><summary aria-label="Ajutor">?</summary><div><strong>Ai nevoie de ajutor?</strong><p>Deschide ghidul pas cu pas pentru configurarea completă a magazinului.</p><a href="<?= e(url('/admin?ghid=1')) ?>">Deschide ghidul de lansare →</a></div></details></div></header><main class="admin-main"><?= $content ?></main></div><div class="admin-order-popup" role="dialog" aria-modal="false" aria-live="polite" hidden data-order-popup><button type="button" data-close-order-popup>×</button><p class="eyebrow">COMANDĂ NOUĂ PRIMITĂ</p><h2 data-popup-title></h2><p data-popup-body></p><a class="admin-button" data-popup-link>Vezi comanda</a></div><div class="admin-confirm-modal" data-confirm-modal hidden><button class="admin-confirm-backdrop" type="button" data-confirm-cancel aria-label="Anulează ștergerea"></button><section class="admin-confirm-card" role="dialog" aria-modal="true" aria-labelledby="admin-confirm-title"><span class="admin-confirm-icon" aria-hidden="true">!</span><p class="eyebrow">CONFIRMARE</p><h2 id="admin-confirm-title">Ștergi acest element?</h2><p data-confirm-message>Elementul va fi arhivat și eliminat din zona publică.</p><div class="button-row"><button class="admin-button secondary" type="button" data-confirm-cancel>Anulează</button><button class="admin-button danger" type="button" data-confirm-accept>Da, șterge</button></div></section></div><div class="toast-region" aria-live="polite" data-toast-region></div><script>window.APP_BASE_PATH=<?= json_encode((string)env('APP_BASE_PATH','')) ?>;</script><script src="<?= e(asset('js/admin.js?v=20260713-11')) ?>" defer></script></body></html>

